const countries = [
    { name: "Afeganistão", code: "AF" },
    { name: "África do Sul", code: "ZA" },
    { name: "Albânia", code: "AL" },
    { name: "Alemanha", code: "DE" },
    { name: "Andorra", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Antígua e Barbuda", code: "AG" },
    { name: "Arábia Saudita", code: "SA" },
    { name: "Argélia", code: "DZ" },
    { name: "Argentina", code: "AR" },
    { name: "Armênia", code: "AM" },
    { name: "Austrália", code: "AU" },
    { name: "Áustria", code: "AT" },
    { name: "Azerbaijão", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Barein", code: "BH" },
    { name: "Bélgica", code: "BE" },
    { name: "Belize", code: "BZ" },
    { name: "Benin", code: "BJ" },
    { name: "Bielorrússia", code: "BY" },
    { name: "Bolívia", code: "BO" },
    { name: "Bósnia e Herzegovina", code: "BA" },
    { name: "Botsuana", code: "BW" },
    { name: "Brasil", code: "BR" },
    { name: "Brunei", code: "BN" },
    { name: "Bulgária", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Butão", code: "BT" },
    { name: "Cabo Verde", code: "CV" },
    { name: "Camarões", code: "CM" },
    { name: "Camboja", code: "KH" },
    { name: "Canadá", code: "CA" },
    { name: "Catar", code: "QA" },
    { name: "Cazaquistão", code: "KZ" },
    { name: "Chade", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China", code: "CN" },
    { name: "Chipre", code: "CY" },
    { name: "Colômbia", code: "CO" },
    { name: "Comores", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Coreia do Norte", code: "KP" },
    { name: "Coreia do Sul", code: "KR" },
    { name: "Costa do Marfim", code: "CI" },
    { name: "Costa Rica", code: "CR" },
    { name: "Croácia", code: "HR" },
    { name: "Cuba", code: "CU" },
    { name: "Dinamarca", code: "DK" },
    { name: "Djibouti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "Egito", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Emirados Árabes Unidos", code: "AE" },
    { name: "Equador", code: "EC" },
    { name: "Eritreia", code: "ER" },
    { name: "Eslováquia", code: "SK" },
    { name: "Eslovênia", code: "SI" },
    { name: "Espanha", code: "ES" },
    { name: "Estados Unidos", code: "US" },
    { name: "Estônia", code: "EE" },
    { name: "Etiópia", code: "ET" },
    { name: "Fiji", code: "FJ" },
    { name: "Filipinas", code: "PH" },
    { name: "Finlândia", code: "FI" },
    { name: "França", code: "FR" },
    { name: "Gabão", code: "GA" },
    { name: "Gâmbia", code: "GM" },
    { name: "Gana", code: "GH" },
    { name: "Geórgia", code: "GE" },
    { name: "Granada", code: "GD" },
    { name: "Grécia", code: "GR" },
    { name: "Guatemala", code: "GT" },
    { name: "Guiana", code: "GY" },
    { name: "Guiné", code: "GN" },
    { name: "Guiné Equatorial", code: "GQ" },
    { name: "Guiné-Bissau", code: "GW" },
    { name: "Haiti", code: "HT" },
    { name: "Honduras", code: "HN" },
    { name: "Hungria", code: "HU" },
    { name: "Iêmen", code: "YE" },
    { name: "Índia", code: "IN" },
    { name: "Indonésia", code: "ID" },
    { name: "Irã", code: "IR" },
    { name: "Iraque", code: "IQ" },
    { name: "Irlanda", code: "IE" },
    { name: "Islândia", code: "IS" },
    { name: "Israel", code: "IL" },
    { name: "Itália", code: "IT" },
    { name: "Jamaica", code: "JM" },
    { name: "Japão", code: "JP" },
    { name: "Jordânia", code: "JO" },
    { name: "Kiribati", code: "KI" },
    { name: "Kuwait", code: "KW" },
    { name: "Laos", code: "LA" },
    { name: "Lesoto", code: "LS" },
    { name: "Letônia", code: "LV" },
    { name: "Líbano", code: "LB" },
    { name: "Libéria", code: "LR" },
    { name: "Líbia", code: "LY" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lituânia", code: "LT" },
    { name: "Luxemburgo", code: "LU" },
    { name: "Macedônia do Norte", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malásia", code: "MY" },
    { name: "Malaui", code: "MW" },
    { name: "Maldivas", code: "MV" },
    { name: "Mali", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Marrocos", code: "MA" },
    { name: "México", code: "MX" },
    { name: "Moçambique", code: "MZ" },
    { name: "Mônaco", code: "MC" },
    { name: "Mongólia", code: "MN" },
    { name: "Montenegro", code: "ME" },
    { name: "Myanmar", code: "MM" },
    { name: "Namíbia", code: "NA" },
    { name: "Nepal", code: "NP" },
    { name: "Nicarágua", code: "NI" },
    { name: "Noruega", code: "NO" },
    { name: "Nova Zelândia", code: "NZ" },
    { name: "Omã", code: "OM" },
    { name: "Paquistão", code: "PK" },
    { name: "Peru", code: "PE" },
    { name: "Portugal", code: "PT" },
  ];
  