-- Migration: Inserção de estados brasileiros
INSERT INTO public.estates (id, name, uf) VALUES
(uuid_generate_v4(), 'Acre', 'AC'),
(uuid_generate_v4(), 'Alagoas', 'AL'),
(uuid_generate_v4(), 'Amapá', 'AP'),
(uuid_generate_v4(), 'Amazonas', 'AM'),
(uuid_generate_v4(), 'Bahia', 'BA'),
(uuid_generate_v4(), 'Ceará', 'CE'),
(uuid_generate_v4(), 'Distrito Federal', 'DF'),
(uuid_generate_v4(), 'Espírito Santo', 'ES'),
(uuid_generate_v4(), 'Goiás', 'GO'),
(uuid_generate_v4(), 'Maranhão', 'MA'),
(uuid_generate_v4(), 'Mato Grosso', 'MT'),
(uuid_generate_v4(), 'Mato Grosso do Sul', 'MS'),
(uuid_generate_v4(), 'Minas Gerais', 'MG'),
(uuid_generate_v4(), 'Pará', 'PA'),
(uuid_generate_v4(), 'Paraíba', 'PB'),
(uuid_generate_v4(), 'Paraná', 'PR'),
(uuid_generate_v4(), 'Pernambuco', 'PE'),
(uuid_generate_v4(), 'Piauí', 'PI'),
(uuid_generate_v4(), 'Rio de Janeiro', 'RJ'),
(uuid_generate_v4(), 'Rio Grande do Norte', 'RN'),
(uuid_generate_v4(), 'Rio Grande do Sul', 'RS'),
(uuid_generate_v4(), 'Rondônia', 'RO'),
(uuid_generate_v4(), 'Roraima', 'RR'),
(uuid_generate_v4(), 'Santa Catarina', 'SC'),
(uuid_generate_v4(), 'São Paulo', 'SP'),
(uuid_generate_v4(), 'Sergipe', 'SE'),
(uuid_generate_v4(), 'Tocantins', 'TO');
