-- Inserindo comodidades básicas para propriedades
INSERT INTO public.amenities (name) VALUES
('Piscina'),
('Academia'),
('Salão de Festas'),
('Quadra Poliesportiva'),
('Churrasqueira'),
('Playground'),
('Espaço Gourmet'),
('Cinema'),
('Sala de Jogos'),
('Piscina Térmica'),
('Sauna'),
('Hidromassagem'),
('Portaria 24h'),
('Elevador'),
('Varanda'),
('Jardim'),
('Área de Serviço'),
('Lavanderia'),
('Cozinha Americana'),
('Armários Embutidos'),
('Closet'),
('Ar Condicionado'),
('Aquecedor'),
('Lareira'),
('Quintal'),
('Garagem Coberta'),
('Vista para o Mar'),
('Vista para Montanhas'),
('Segurança 24h'),
('Sistema de Alarme'),
('Câmeras de Segurança'),
('Acesso para Deficientes'),
('Pet Friendly'),
('Mobiliado'),
('Internet Fibra Óptica'),
('Gerador de Energia'),
('Sistema de Energia Solar'),
('Cisterna'),
('Poço Artesiano');